version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "typescript"
        versions:
          - ">=6.1.0"
    groups:
      npm-dependencies:
        patterns:
          - "*"
